name: Integration tests

on:
  # Trigger the workflow on pull request,
  # but only for the main branch
  pull_request:
    branches:
      - main
env:
  PORT: 3100
  EMAIL_API_KEY: 'SOME-LONG-SECRET-KEY'
  APP_SECRET: 'SOME-LONG-SECRET-KEY'
  CLOUDINARY_SECRET: CLOUDINARY_SECRET
  CLOUDINARY_KEY: CLOUDINARY_KEY
  PARTNERS_PORTAL_URL: http://localhost:3001
  DATABASE_URL: postgres://bloom-dev:bloom@localhost:5432/bloom
  TEST_DATABASE_URL: postgres://bloom-dev:bloom@localhost:5432/bloom_test

jobs:
  integration-tests:
    name: Run integration tests
    runs-on: ubuntu-latest

    steps:
      - name: Check out Git repository
        uses: actions/checkout@v2

      - name: Set up Node.js
        uses: actions/setup-node@v1
        with:
          node-version: 18

      - name: yarn in root dir
        run: yarn

      - name: yarn in backend/core dir
        working-directory: ./backend/core
        run: yarn

      - name: install postgres
        run: sudo apt install postgresql

      - name: add postgres user
        run: psql -h postgres -U postgres_user -c 'create user "bloom-dev" with password "bloom";'

      - name: yarn e2e tests backend
        run: yarn test:e2e:backend:core
