name: Integration tests

on:
  # Trigger the workflow on pull request,
  # but only for the main branch
  pull_request:
    branches:
      - main
env:
  PORT: 3100
  EMAIL_API_KEY: 'SOME-LONG-SECRET-KEY'
  APP_SECRET: 'SOME-LONG-SECRET-KEY'
  CLOUDINARY_SECRET: CLOUDINARY_SECRET
  CLOUDINARY_KEY: CLOUDINARY_KEY
  PARTNERS_PORTAL_URL: http://localhost:3001
  DATABASE_URL: postgres://bloom-dev:bloom@localhost:5432/bloom
  TEST_DATABASE_URL: postgres://bloom-dev:bloom@localhost:5432/bloom_test

jobs:
  postgres-job:
    runs-on: ubuntu-latest
    services:
      postgres:
        image: postgres
        env:
          POSTGRES_USERNAME: bloom-dev
          POSTGRES_PASSWORD: bloom
        options: --health-cmd pg_isready --health-interval 10s --health-timeout 5s --health-retries 5
        ports:
          # Maps TCP port 5432 in the service container to a randomly chosen available port on the host.
          - 5432

  integration-tests:
    name: Run integration tests
    runs-on: ubuntu-latest

    steps:
      - name: Check out Git repository
        uses: actions/checkout@v2

      - name: Check postgres
        run: pg_isready -h localhost -p ${{ job.services.postgres.ports[5432] }}

      - name: Set up Node.js
        uses: actions/setup-node@v1
        with:
          node-version: 18

      - name: yarn in root dir
        run: yarn

      - name: yarn in backend/core dir
        working-directory: ./backend/core
        run: yarn

      - name: yarn e2e tests backend
        run: yarn test:e2e:backend:core
